### PR TITLE
added erb template

### PR DESCRIPTION
**Pull request by fschwahn**
Hi,
this is a pull request for issue #3. Unfortunately, I couldn't run the tests due to the dependency on mongodb. I had to regenerate the gemspec to test it with my app.

Best regards,
Fabian

### CODE REVIEW

**Comment by logankoester** [comment]
Looks good! Perhaps a similar solution should be applied to the Mongo dependency? I'm not sure we should actually keep the haml template around, since template changes would not be DRY and it provides no real benefit.

**Comment by fschwahn** [comment]
after I updated the gem I'm getting the following error message:

```
Invalid gemspec in [/path/to/.rvm/gems/ree-1.8.7-2011.03/specifications/errship-2.1.1.gemspec]: Illformed requirement ["#<YAML::Syck::DefaultKey:0x108c99510> 0.8.7"]
```

I installed it was ree and mri1.8.7, happens with both. It's very strange because your gemspec looks fine in the repository...

**Comment by logankoester** [comment]
Any luck getting this working? I don't know many people running Rails 3.1 on REE or 1.8 - do you have the same issue on more recent rubies?

**Comment by fschwahn** [comment]
Ok, I just googled a bit, and this has nothing to do with rails, it is a ruby 1.8.7 issue. The problem is the dependency on rake 0.8.7, this dependency is not parsed correctly for 1.8.7 .
I think the issue can be solved if you define the dependency on rake as >= 0.8.7, and regenerate the gemspec.

**Pull request merged**
