### PR TITLE
Rake update

### PR DESCRIPTION
**Pull request by czarneckid**
Remove explicit Rake version dependency for 1.8.7 compatibility. Version bump. gemspec update.

### CODE REVIEW

**Comment by czarneckid** [comment]
This should address @fschwahn 's issues from #5.

**Comment by fschwahn** [comment]
cool, if you release the gem i can test it. But actually I'm not quite sure that is the problem. If you look at rubygems.org you can compare these version:
- https://rubygems.org/gems/errship/versions/2.1.1
- https://rubygems.org/gems/errship/versions/2.0.1

You can see that the 'Development Dependencies' for 2.1.1 are wrong, and for 2.0.1 it is right, even though it is also an explicit version requirement.

**Comment by fschwahn** [comment]
Ok, here is some more information: https://github.com/carlhuda/bundler/issues/1320
Summary:

```
The short answer is: only release from Ruby 1.8.

The longer answer is: the very latest Rubygems running on 1.9 with libyaml and psych might work, but I'm not positive.
```

**Comment by fschwahn** [comment]
Hey, could you release the gem with the updated dependency or do the release with 1.8.7? Then I can test if the problem with 1.8.7 is solved. Thanks!

**Comment by czarneckid** [comment]
errship 2.1.2 has been released today.

**Comment by fschwahn** [comment]
great, it works not. thank you very much!

**Pull request merged**
